### ISSUE TITLE
reported errors

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone-dark-mode#13]
Reported by @monikarao
* [ ] Front-end - Button is not aligned to the Site Identity section - https://a.cl.ly/4guJWbke 
* [ ] Focus button border color not looks good - https://a.cl.ly/o0umOjy7
* [ ] Button Position on Mobile - https://a.cl.ly/Z4uy2JJp

**Comment by aristath** [comment]
Reported by @francescamarano
Full screen:
1. Enter full-screen with dark mode off in Chrome
2. Clicking on Dark Mode On > Whole page goes dark :white_check_mark:
3. Clicking on Dark Mode Off > Goes back to original palette :white_check_mark:  but toggle does not become dark :octagonal_sign:
4. To get the toggle to become dark you need to click outside of the toggle
5. Hover doesn’t change the color
6. Clicking Dark Mode On > Whole page goes dark, but no contrasting color in the toggle
7. Clicking on edit > Inside the post, the toggle has a black background so can not be red.
8. Clicking on “Edit post” in the horizontal bar > Dark Mode is off

<img width="1792" alt="dark-mode-back-from-on-to-editor" src="https://user-images.githubusercontent.com/588688/97717781-d8a14e80-1acd-11eb-8d1f-0fa20b8aca7f.png">
<img width="1792" alt="dark-mode-back-from-off" src="https://user-images.githubusercontent.com/588688/97717798-dc34d580-1acd-11eb-90f5-3488a2f5bad8.png">

**Comment by JustinyAhin** [comment]
> Reported by @MonikaRao
> 
> * [ ]  Front-end - Button is not aligned to the Site Identity section - https://a.cl.ly/4guJWbke

I'm wondering if this is really a bug and should fixed. I think the button is placed a bit at the top intentionally. Because when there is a menu, it is placed at the right of the screen.

![Screenshot_2020-11-01 two wordpress test – Just another WordPress site](https://user-images.githubusercontent.com/33403964/97800038-1dde9100-1c32-11eb-92e2-82bc60e8043c.png)

**Comment by JustinyAhin** [comment]
>  Focus button border color not looks good - https://a.cl.ly/o0umOjy7

I think this has already been fixed. ? @aristath 

Focus in dark mode
![dark-mode-focus](https://user-images.githubusercontent.com/33403964/97840037-9d786880-1ce3-11eb-964d-85eefa1a5cca.png)

Focus in light mode
![light-mode-focus](https://user-images.githubusercontent.com/33403964/97840041-9e10ff00-1ce3-11eb-8722-4c06b16a2fa6.png)


On Google Chrome

**Comment by JustinyAhin** [comment]
> Button Position on Mobile - https://a.cl.ly/Z4uy2JJp

Tracked in #9

**Comment by aristath** [comment]
I believe all issues here were fixed with 2 changes we made:
* Toggle is now fixed on the bottom-right instead of the header.
* Reversed the buttons color scheme and pushed some additional fixes
