### ISSUE TITLE
In non-fullscreen mode the button is not fully visible

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone-dark-mode#14]
<img width="1260" alt="Screenshot 2020-10-30 at 15 20 45" src="https://user-images.githubusercontent.com/588688/97716515-61b78600-1acc-11eb-8d81-10573896b0ba.png">

**Comment by carolinan** [comment]
Ipad portrait mode:

<img width="480" alt="thumbnail" src="https://user-images.githubusercontent.com/7422055/97836422-9568fa80-1cdc-11eb-8f83-d00e16bc22cc.png">

(No issues in landscape)
