### ISSUE TITLE
Toggle doesn't work if you don't have Dark Mode on

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone-dark-mode#3]
If you don't have Dark Mode enabled, you can still see the toggle, but it doesn't do anything:

![dark-mode-toggle](https://user-images.githubusercontent.com/2846578/97592503-1a9b9900-19d7-11eb-9120-3fcdf3c86e41.gif)

Can the toggle work regardless of your browser/OS settings?

**Comment by aristath** [comment]
Ah good point! Yes, sure we can make it work regardless of the OS setting and just default to the OS value.
Assigned to myself and will be fixed tomorrow morning
