### ISSUE TITLE
A11y review of the new dark-mode toggler implementation

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone-dark-mode#5]
After the discussion on #1 and a private chat with @afercia about what "the perfect toggler" would be from an a11y perspective, it was refactored but we'll need a final review of this, just to be sure we're OK for screen-readers and as an overall experience.

This should go through a final a11y check to make sure what was discussed was properly implemented. 🙇

**Comment by afercia** [comment]
Tested it and from an accessibility perspective seems a very good implementation to me.

A toggle button (i.e. a button with a state) is visually and semantically the simplest, most accessible solution. Tested with maor screen reader/browser combinations on Windows and macOS, Voice Control on macOS 👍

**Comment by aristath** [comment]
Perfect, thank you!
Closing this one 👍
