### ISSUE TITLE
Hide the dark mode toggle button from Internet Explorer 11

### ISSUE THREAD

**Issue by afercia** [WordPress/twentytwentyone-dark-mode#6]
Consider to hide the dark mode toggle button from Internet Explorer 11 as it doesn't do anything with that browser. I think Twenty Twenty One already adds a `is-IE` CSS class to the body that could be used for this purpose (If there's a quick way to not print out the button at all, that would be even better).

**Comment by aristath** [comment]
Good catch! Fixed, now on IE the extra styles, scripts and the button don't get added 👍
