### ISSUE TITLE
The dark mode button hide the site title when it doesn't wrap

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/twentytwentyone-dark-mode#9]
By default the site title is designed to wrap to a new line when it meets a space.
But when the title is long and has no space inside, a part of it is hidden by the dark mode button.

![Capture d’écran du 2020-10-30 15-00-34](https://user-images.githubusercontent.com/33403964/97713907-be14a880-1ac0-11eb-92d3-58a23cb84c22.png)

**Comment by JustinyAhin** [comment]
What could be done here:

On mobile, add a 44px margin-top to the `<header>` element. And move the dark mode button to the top of the page. It'll look like this

![screenshot-two wordpress test-2020 11 02-09_54_33](https://user-images.githubusercontent.com/33403964/97848698-be47ba80-1cf1-11eb-908e-1651ecf170dd.png)

**Comment by aristath** [comment]
No longer an issue, for the purposes of beta [it was decided](https://wordpress.slack.com/archives/C02RP4VMP/p1604321014437100) to put the toggle on the bottom-right instead of the header
